# Generated by Django 3.0.3 on 2020-06-08 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('variables', models.CharField(blank=True, max_length=256, null=True)),
                ('model', models.BinaryField(blank=True, null=True)),
                ('dataset', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('start_latitude', models.FloatField(max_length=12)),
                ('start_longitude', models.FloatField(max_length=12)),
                ('end_latitude', models.FloatField(max_length=12)),
                ('end_longitude', models.FloatField(max_length=12)),
                ('o_latitude', models.FloatField(max_length=12)),
                ('o_longitude', models.FloatField(max_length=12)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Location')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('comments', models.CharField(max_length=256)),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='PreProcessingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('config', models.CharField(max_length=512)),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('result', models.FloatField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.AnalyticalModel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.AnalyticalModel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('data', models.BinaryField()),
                ('comments', models.CharField(max_length=256)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.AnalyticalModel')),
            ],
        ),
        migrations.CreateModel(
            name='LocationMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Location')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Workflow'),
        ),
        migrations.AddField(
            model_name='analyticalmodel',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Workflow'),
        ),
        migrations.CreateModel(
            name='AccessControlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_id', models.CharField(max_length=32)),
                ('object_id', models.CharField(max_length=32)),
                ('object_type', models.CharField(choices=[('Location', 'Location'), ('Workflow', 'Workflow'), ('AnalyticalModel', 'AnalyticalModel'), ('Dataset', 'Dataset')], max_length=15)),
                ('expiration', models.DateTimeField()),
                ('access_type', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write')], max_length=5)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
