# Generated by Django 3.0.3 on 2020-08-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetmetadata',
            old_name='model_id',
            new_name='dataset_id',
        ),
    ]
