# Generated by Django 3.0.3 on 2020-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmodel',
            name='dataset',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='analyticalmodel',
            name='model',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='analyticalmodel',
            name='variables',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
