# Generated by Django 3.0.3 on 2020-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_django', '0002_auto_20200528_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmodel',
            name='dataset',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='analyticalmodel',
            name='model',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticalmodel',
            name='variables',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
