# Generated by Django 3.0.3 on 2020-08-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_django', '0002_auto_20200810_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetmetadata',
            old_name='dataset_id',
            new_name='base_id',
        ),
        migrations.RenameField(
            model_name='locationmetadata',
            old_name='location_id',
            new_name='base_id',
        ),
        migrations.RenameField(
            model_name='modelmetadata',
            old_name='model_id',
            new_name='base_id',
        ),
    ]
