# Generated by Django 3.0.3 on 2020-05-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_django', '0003_auto_20200528_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrollist',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='accesscontrollist',
            old_name='target_user',
            new_name='target_user_id',
        ),
        migrations.RenameField(
            model_name='analyticalmodel',
            old_name='workflow',
            new_name='workflow_id',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='workflow',
            new_name='workflow_id',
        ),
        migrations.RenameField(
            model_name='datasetmetadata',
            old_name='model',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='locationmetadata',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='modeldata',
            old_name='model',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='modelmetadata',
            old_name='model',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='modelresults',
            old_name='model',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='workflowresults',
            old_name='dataset',
            new_name='dataset_id',
        ),
        migrations.RenameField(
            model_name='workflowresults',
            old_name='workflow',
            new_name='workflow_id',
        ),
    ]
